### ISSUE TITLE
Error when trying to convert concurrent big files

### ISSUE THREAD

**Issue by piKolin** [jodconverter/jodconverter#306]
Hi!

We have two nodes of jodconverter in production that receives four files to convert by node, and works well, except when somebody send a report that take more than 2-3 minutes to process. In this cases, the other files, are discarded because "No office manager available".

**Maven dependencies**
```xml
<dependency>
	<groupId>net.sf.jodreports</groupId>
	<artifactId>jodreports</artifactId>
	<version>2.4.0</version>
</dependency>
<dependency>
	<groupId>org.jodconverter</groupId>
	<artifactId>jodconverter-local</artifactId>
	<version>4.4.2</version>
</dependency>
```

**The build() configuration of JOD:**
```java
LocalOfficeManager.builder()
    .portNumbers(2004)
    .officeHome("/opt/libreoffice7.1")
    .taskExecutionTimeout(360000)
    .taskQueueTimeout(60000)
    .maxTasksPerProcess(0)
    .build();
```

**Error:**
```
org.jodconverter.core.office.OfficeException: No office manager available after 60000 millisec
```

We tried to configure some another `portNumbers` (from 2 to 6 ports), and different values for `maxTasksPerProcess` (25, 50, 200), with the same results.

**NOTE**: Increase `taskQueueTimeout` can't be possible due to scheduler/proxy timeout

**Anyone knows what's the problem with configuration?**

Thanks!

**Comment by sbraconnier** [comment]
Would it be possible for you to provide a detailed log file (mode debug) in order see exactly what's going on??

The `portNumbers` will start an office process for each specified ports, so it's also the number of conversions that can be done at the same time. You may want to play with that a little.

Could you also show me how the conversion is done (source code)?

Thanks.

**Comment by piKolin** [comment]
Thx for the reply, @sbraconnier.

We tried to configure 6 `portNumbers`, but with the same result.

Source code of conversion:
```java
File output = new File(filePath);
OfficeManager manager = OfficeManagerHolder.getInstance().getOfficeManager();        
LocalConverter converter = LocalConverter.make(manager);
try {
    DocumentFormat documentFormat = converter.getFormatRegistry().getFormatByExtension(extension);
    PdfDocumentFilterFactory.addPdfFilters(documentFormat, format);
    converter.convert(input)
            .to(output)
            .as(documentFormat).execute();
} catch (Exception e) {
    LOGGER.error("Error de conversión de documento: {}", input, e);
    throw new ServiceException("", e);
}
```

Always get the same error:

```txt
yyyy-MM-dd HH:MM:ss|ERROR|http-nio-8080-exec-3|Error de conversiÃ³n de documento: /srv/apache-tomcat-instance-9.0.50/share/temp/jodrws/00727688-f0b9-46fe-b8e6-1448f0dad80f/input.odt| org.jodconverter.core.office.OfficeException: No office manager available after 60000 millisec
    at org.jodconverter.core.office.AbstractOfficeManagerPool.acquireManager(AbstractOfficeManagerPool.java:180)
    at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:216)
    at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:149)
    at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:62)
    at es.example.org.jodrws.service.impl.DocumentConverterServiceImpl.convert(DocumentConverterServiceImpl.java:84)
...
```

The line 84 at error, corresponds with `.as(documentFormat).execute();`

Any ideas??

**Comment by sbraconnier** [comment]
I see you are getting the office manager from a `OfficeManagerHolder` instance. Can you share the code where this instance is set (with the manager configuration) ?

And is it possible for you to share a full log file in debug mode where I could see what's going on?? If no manager is available (you are suppose to have 1 per port), it means they are all currently used by a thread. I would like to see in the log files when the conversions started for those threads.

**Comment by piKolin** [comment]
Ofc, this is the class to configure and create an instance:

```java
package -----.jodrws.service;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.jodconverter.core.office.OfficeManager;
import org.jodconverter.local.office.LocalOfficeManager;

import ------.utils.BaseUtils.Configuration;

public final class OfficeManagerHolder {

    private static final Logger LOGGER = LogManager.getLogger(OfficeManagerHolder.class);
    private static final String COMMA = ",";
    private OfficeManager officeManager;

    private static final long DEFAULT_TASK_EXECUTION_TIMEOUT = 30000L;

    private static final long DEFAULT_TASK_QUEUE_TIMEOUT = 30000L;

    private OfficeManagerHolder() {

        try {
            officeManager = configure(LocalOfficeManager.builder()).build();
        } catch (Exception ex) {
            LOGGER.error("Error creando instancia de OfficeManager ", ex);
        }
    }

    public static OfficeManagerHolder getInstance() {
        return LazyHolder.INSTANCE;
    }

    public OfficeManager getOfficeManager() {
        return officeManager;
    }

    private LocalOfficeManager.Builder configure(LocalOfficeManager.Builder builder) {

        LOGGER.info("Entrando en configure ----------------------");
        builder.taskExecutionTimeout(DEFAULT_TASK_EXECUTION_TIMEOUT);
        builder.taskQueueTimeout(DEFAULT_TASK_QUEUE_TIMEOUT);

        String officeHome = Configuration.getProperty("office.home");
        if (officeHome != null) {
            builder.officeHome(officeHome);
            LOGGER.debug("Estableciendo office.home: {}", officeHome);
        }

        String pipeNames = Configuration.getProperty("office.manager.pipe.names");
        if (pipeNames != null) {
            builder.pipeNames(pipeNames.split(COMMA));
            LOGGER.debug("Estableciendo office.manager.pipe.names: {}", pipeNames);
        }

        String socketPorts = Configuration.getProperty("office.manager.socket.ports");
        if (socketPorts != null) {
            
            List<String> stringPortList = new ArrayList<>(Arrays.asList(socketPorts.split(COMMA)));
            
            int[] ports = stringPortList.stream()
                    .map(String::trim)
                    .map(Integer::valueOf)
                    .mapToInt(i->i)
                    .toArray();
            
            builder.portNumbers(ports);
            LOGGER.info("Estableciendo office.manager.socket.ports: {}", socketPorts);
        }

        String timeout = Configuration.getProperty("office.manager.timeout");
        if (timeout != null) {
            builder.taskExecutionTimeout(Long.parseLong(timeout));
            LOGGER.debug("Estableciendo office.manager.timeout: {}", timeout);
        }

        String maxTasksPerProcess = Configuration.getProperty("office.manager.max.tasks.per.process");
        if (maxTasksPerProcess != null) {
            builder.maxTasksPerProcess(Integer.parseInt(maxTasksPerProcess));
            LOGGER.debug("Estableciendo office.manager.max.tasks.per.process: {}", maxTasksPerProcess);
        }

        String taskQueueTimeout = Configuration.getProperty("office.manager.task.queue.timeout");
        if (taskQueueTimeout != null) {
            builder.taskQueueTimeout(Long.parseLong(taskQueueTimeout));
            LOGGER.debug("Estableciendo office.manager.task.queue.timeout: {}", taskQueueTimeout);
        }
        
        LOGGER.info("==========================================");
        return builder;
    }

    private static final class LazyHolder {

        private static final OfficeManagerHolder INSTANCE = new OfficeManagerHolder();

        private LazyHolder() {

        }

    }

}

```

If i run the application with some ports configured in `portNumbers`, when i execute a conversion, the jodconverter balance between the available OfficeManagers ?

Can i check, if the ports really opened ? Or force a conversion to an especific port ?

I will try to run a test in debug mode this afternoon, and share it in this issue.

Thx!!

**Comment by sbraconnier** [comment]
> If i run the application with some ports configured in portNumbers, when i execute a conversion, the jodconverter balance between the available OfficeManagers ?

Yes

> Can i check, if the ports really opened ?

You can use netstat on windows, or something else if you are using another os. Search on google to know the command for your os.

> Or force a conversion to an especific port ?

No, you can't do that

> I will try to run a test in debug mode this afternoon, and share it in this issue.

Perfect!

**Comment by sbraconnier** [comment]
I'll close this one as inactive. Feel free to reopen if needed!
