### ISSUE TITLE
Could not store document: tempfile_1.pdf

### ISSUE THREAD

**Issue by SamehArmouche** [jodconverter/jodconverter#329]
I try convert .ppt to pdf and just in 3 files I get this error:

```console
org.jodconverter.core.office.OfficeException: Could not store document: tempfile_1.pdf
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:198) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:131) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81) ~[jodconverter-core-4.4.6.jar:4.4.6]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.sun.star.io.IOException: SfxBaseModel::impl_store <file:///C:/Users/SAMEH~1.ARM/AppData/Local/Temp/.jodconverter_28461dbb-dc26-4333-8ce9-b2ac08764752/tempfile_1.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16)

```

Any Help?

**Comment by Birddle** [comment]
The same problem, i using mac and got this error.

**Comment by SamehArmouche** [comment]
@Birddle I found the solution, you have to install LibreOffice_7.4.6_Win_x64 because the latest version doesn't work

**Comment by Birddle** [comment]
> @Birddle I found the solution, you have to install LibreOffice_7.4.6_Win_x64 because the latest version doesn't work
Already uninstall this and back to PDFBox🥲
