### ISSUE TITLE
Can not convert .pdf to .docx

### ISSUE THREAD

**Issue by Birddle** [jodconverter/jodconverter#330]
I convert a .pdf to .docx, but when i open the docx in local, it tips:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/86408260/227706961-f8eb4c54-bf4b-4afe-9e61-68fd99c692d3.png">

there is my converter code:

```
import org.jodconverter.core.DocumentConverter;


private DocumentConverter documentConverter;

public void convertPDFtoWord(File file)  throws IOException, InvalidFormatException, OfficeException  {

       String fileName = EXPORT_PATH + file.getName().split("\\.")[0] + ".docx”;

        documentConverter.convert(file).as(DefaultDocumentFormatRegistry.PDF)
                .to(new File(fileName)).as(DefaultDocumentFormatRegistry.DOCX)
                .execute();
}
 
```
There is error log:

```
2023-03-25T19:56:45.785+08:00  INFO 1481 --- [ter-poolentry-1] o.j.local.task.LocalConversionTask       : Executing local conversion task [pdf -> docx]...
2023-03-25 19:56:45.906 soffice[1491:56597] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007ff8108f01e6 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 338
	1   AppKit                              0x00007ff8108dc713 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1247
	2   AppKit                              0x00007ff8108dc22d -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	3   libvcl.dylib                        0x000000010e99e1f6 -[SalFrameWindow initWithSalFrame:] + 262
	4   libvcl.dylib                        0x000000010e6d6d93 _ZN12AquaSalFrame17initWindowAndViewEv + 643
	5   libvcl.dylib                        0x000000010e6d69d7 _ZN12AquaSalFrameC2EP8SalFramem + 519
	6   libvcl.dylib                        0x000000010e6b1f10 _ZN15AquaSalInstance11CreateFrameEP8SalFramem + 48
	7   libvcl.dylib                        0x000000010e9684d7 _ZN6Window8ImplInitEPS_lP16SystemParentData + 1159
	8   libvcl.dylib                        0x000000010e8ec184 _ZN16ImplBorderWindow8ImplInitEP6WindowltP16SystemParentData + 404
	9   libvcl.dylib                        0x000000010e8ec4c5 _ZN16ImplBorderWindowC1EP6WindowP16SystemParentDatalt + 69
	10  libvcl.dylib                        0x000000010e987ee8 _ZN10WorkWindow8ImplInitEP6WindowlP16SystemParentData + 88
	11  libvcl.dylib                        0x000000010e988290 _ZN10WorkWindowC1EP6Windowl + 80
	12  libootk.dylib                       0x000000010d7500c0 _ZN11VCLXToolkit16ImplCreateWindowEPP10VCLXWindowRKN3com3sun4star3awt16WindowDescriptorEP6Windowl + 5712
	13  libootk.dylib                       0x000000010d74e454 _ZN11VCLXToolkit16ImplCreateWindowERKN3com3sun4star3awt16WindowDescriptorEl + 452
	14  libootk.dylib                       0x000000010d74e7b4 _ZThn80_N11VCLXToolkit12createWindowERKN3com3sun4star3awt16WindowDescriptorE + 20
	15  libfwk.dylib                        0x000000011392559e _ZN9framework18TaskCreatorService28implts_createContainerWindowERKN3com3sun4star3uno9ReferenceINS3_3awt7XWindowEEERKNS6_9RectangleEh + 1022
	16  libfwk.dylib                        0x0000000113924c1c _ZN9framework18TaskCreatorService27createInstanceWithArgumentsERKN3com3sun4star3uno8SequenceINS4_3AnyEEE + 924
	17  libfwk.dylib                        0x0000000113926a22 _ZThn16_N9framework18TaskCreatorService27createInstanceWithArgumentsERKN3com3sun4star3uno8SequenceINS4_3AnyEEE + 18
	18  libfwk.dylib                        0x000000011382c2e1 _ZN9framework11TaskCreator10createTaskERKN3rtl8OUStringEh + 3089
	19  libfwk.dylib                        0x00000001138f3aea _ZN9framework7Desktop9findFrameERKN3rtl8OUStringEi + 778
	20  libfwk.dylib                        0x00000001138f4102 _ZThn56_N9framework7Desktop9findFrameERKN3rtl8OUStringEi + 18
	21  libfwk.dylib                        0x00000001138ad11e _ZN9framework7LoadEnv16impl_loadContentEv + 766
	22  libfwk.dylib                        0x00000001138a8ba6 _ZN9framework7LoadEnv12startLoadingEv + 438
	23  libfwk.dylib                        0x00000001138a7c43 _ZN9framework7LoadEnv20loadComponentFromURLERKN3com3sun4star3uno9ReferenceINS3_5frame16XComponentLoaderEEERKNS5_INS3_4lang20XMultiServiceFactoryEEERKN3rtl8OUStringESJ_iRKNS4_8SequenceINS3_5beans13PropertyValueEEE + 227
	24  libfwk.dylib                        0x00000001138f2a87 _ZN9framework7Desktop20loadComponentFromURLERKN3rtl8OUStringES4_iRKN3com3sun4star3uno8SequenceINS7_5beans13PropertyValueEEE + 327
	25  libfwk.dylib                        0x00000001138f2bd2 _ZThn24_N9framework7Desktop20loadComponentFromURLERKN3rtl8OUStringES4_iRKN3com3sun4star3uno8SequenceINS7_5beans13PropertyValueEEE + 18
	26  libs5abi_uno.dylib                  0x00000001107a4ada _ZN7bridges7cpp_uno6shared25unoInterfaceProxyDispatchEP14_uno_InterfacePK24_typelib_TypeDescriptionPvPS7_PP8_uno_Any + 4042
	27  libs5abi_uno.dylib                  0x00000001107a4430 _ZN7bridges7cpp_uno6shared25unoInterfaceProxyDispatchEP14_uno_InterfacePK24_typelib_TypeDescriptionPvPS7_PP8_uno_Any + 2336
	28  libs5abi_uno.dylib                  0x00000001107a3df0 _ZN7bridges7cpp_uno6shared25unoInterfaceProxyDispatchEP14_uno_InterfacePK24_typelib_TypeDescriptionPvPS7_PP8_uno_Any + 736
	29  binaryurp.uno.dylib                 0x00000001186fe864 _ZNK9binaryurp15IncomingRequest13execute_throwEPNS_9BinaryAnyEPNSt3__16vectorIS1_NS3_9allocatorIS1_EEEE + 2068
	30  binaryurp.uno.dylib                 0x00000001186fdb4b _ZNK9binaryurp15IncomingRequest7executeEv + 155
	31  binaryurp.uno.dylib                 0x00000001187027af request + 15
	32  libuno_cppu.dylib.3                 0x000000010abf2d76 _ZN15cppu_threadpool8JobQueue5enterElh + 150
	33  libuno_cppu.dylib.3                 0x000000010abf3171 _ZN15cppu_threadpool14ORequestThread3runEv + 97
	34  libuno_cppu.dylib.3                 0x000000010abf30ce cppu_requestThreadWorker + 14
	35  libuno_sal.dylib.3                  0x000000010a976855 osl_setThreadTextEncoding + 309
	36  libsystem_pthread.dylib             0x00007ff80d765259 _pthread_start + 125
	37  libsystem_pthread.dylib             0x00007ff80d760c7b thread_start + 15
)
2023-03-25T19:56:46.349+08:00 ERROR 1481 --- [ter-poolentry-1] o.j.local.task.LocalConversionTask       : Local conversion failed.

org.jodconverter.core.office.OfficeException: Could not store document: tempfile_2.docx; errorCode: 2074
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:195) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:131) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81) ~[jodconverter-core-4.4.6.jar:4.4.6]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.sun.star.task.ErrorCodeIOException: 
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173) ~[jurt-4.1.2.jar:na]
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139) ~[jurt-4.1.2.jar:na]
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334) ~[jurt-4.1.2.jar:na]
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303) ~[jurt-4.1.2.jar:na]
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87) ~[jurt-4.1.2.jar:na]
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636) ~[jurt-4.1.2.jar:na]
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146) ~[jurt-4.1.2.jar:na]
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128) ~[jurt-4.1.2.jar:na]
	at jdk.proxy2/jdk.proxy2.$Proxy216.storeToURL(Unknown Source) ~[na:na]
	at org.jodconverter.local.task.LocalConversionTask.storeDocumentToURL(LocalConversionTask.java:214) ~[jodconverter-local-4.4.6.jar:4.4.6]
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:192) ~[jodconverter-local-4.4.6.jar:4.4.6]
	... 8 common frames omitted
```

**Comment by sbraconnier** [comment]
Sorry for the late answer.

I found out that you have to force the input/output filters used when loading/storing documents. I'll try to find a way to improve how it can be done. But for now, try this:

```java
final File pdf = new File("test.pdf");
final File docx = new File("test.docx");

Map<String,Object> loadProps = new HashMap<>();
loadProps.put("FilterName", "writer_pdf_import");
Map<String,Object> storeProps = new HashMap<>();
storeProps.put("FilterName", "writer8");
LocalConverter
        .builder()
        .officeManager(manager)
        .loadProperties(loadProps)
        .storeProperties(storeProps)
        .build()
        .convert(pdf)
        .as(DefaultDocumentFormatRegistry.PDF)
        .to(docx)
        .as(DefaultDocumentFormatRegistry.DOCX)
        .execute();
```
