### ISSUE TITLE
Using SpringBoot autoconfiguration with a remote setup fails with ClassNotFoundException

### ISSUE THREAD

**Issue by SchlauFuchs** [jodconverter/jodconverter#331]
Hi,

we are trying to use JodConverter in a remote setup, as in having the conversion happening in a separate docker image with LibreOffice installed, plus having a Springboot app there that exposes port 2002 and 8080 (mostly following the sample code)

Our main SpringBoot app (V2.7.10) is now supposed to use the remote setup of JodConverter using the settings in application.yaml:

```yaml
jodconverter:
  remote:
    enabled: true
    url: localhost:2002
```

the dependencies defined in build.gradle.kts:

```kotlin
    implementation("org.jodconverter:jodconverter-spring-boot-starter:4.4.6")
    implementation("org.jodconverter:jodconverter-remote:4.4.6")
```
Starting this application fails with a `ClassNotFoundException` in context configuration:

```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.jodconverter.boot.autoconfigure.JodConverterLocalProperties]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class org.jodconverter.boot.autoconfigure.JodConverterLocalProperties
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.10.jar:2.7.10]
	at OurApp(OurApp.kt:28) ~[main/:na]
	at OurApp.main(OurApp.kt) ~[main/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class org.jodconverter.boot.autoconfigure.JodConverterLocalProperties
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:162) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:402) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:325) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202) ~[spring-context-5.3.26.jar:5.3.26]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:177) ~[spring-context-5.3.26.jar:5.3.26]
	... 14 common frames omitted
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.jodconverter.boot.autoconfigure.JodConverterLocalProperties] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@1d44bcfa]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:459) ~[spring-core-5.3.26.jar:5.3.26]
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:151) ~[spring-core-5.3.26.jar:5.3.26]
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/jodconverter/local/task/LoadDocumentMode
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467) ~[spring-core-5.3.26.jar:5.3.26]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.jodconverter.local.task.LoadDocumentMode
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 25 common frames omitted
```

We tried adding jodconverter-local to the dependencies but the problem did not go away. Any recommendations?

**Comment by sbraconnier** [comment]
Sorry for the late anwser.

As see this as a bug. I tried different ways but for now you'll have to include the `jodconverter-local` dependency (don't forget to reload your gradle project if you're using intellij), and exclude the `JodConverterLocalAutoConfiguration`.

In your build.gradle.kts:

```
    implementation("org.jodconverter:jodconverter-spring-boot-starter:4.4.6")
    implementation("org.jodconverter:jodconverter-local:4.4.6")
    implementation("org.jodconverter:jodconverter-remote:4.4.6")
```

In your application.yml:
```
spring:
  autoconfigure:
    exclude: org.jodconverter.boot.autoconfigure.JodConverterLocalAutoConfiguration
jodconverter:
  remote:
    enabled: true
    url: localhost:2002
```

**Comment by TomDeBacker** [comment]
We are also running into this issue using 

`<dependency>
  <groupId>org.jodconverter</groupId>
  <artifactId>jodconverter-local-lo</artifactId>
  <version>4.4.5</version>
</dependency>`

**Comment by DeminIgor** [comment]
> Привет,
> 
> мы пытаемся использовать JodConverter при удаленной настройке, например, преобразование происходит в отдельном образе докера с установленным LibreOffice, а также имеется приложение Springboot, которое обеспечивает порты 2002 и 8080 (в основном согласно примеру кода)
> 
> В нашем последнем приложении SpringBoot (V2.7.10) теперь следует использовать удаленный поток JodConverter с использованием настроек в application.yaml:
> 
> ```yaml
> jodconverter:
>   remote:
>     enabled: true
>     url: localhost:2002
> ```
> 
> в зависимости от режима в build.gradle.kts:
> 
> ```kotlin
>     implementation("org.jodconverter:jodconverter-spring-boot-starter:4.4.6")
>     implementation("org.jodconverter:jodconverter-remote:4.4.6")
> ```
> 
> Запуск этого решения завершается неудачно `ClassNotFoundException`сконфигурацией в десятки раз:
> 
> ```
> org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.jodconverter.boot.autoconfigure.JodConverterLocalProperties]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class org.jodconverter.boot.autoconfigure.JodConverterLocalProperties
> 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.10.jar:2.7.10]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.10.jar:2.7.10]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.10.jar:2.7.10]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.10.jar:2.7.10]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.10.jar:2.7.10]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.10.jar:2.7.10]
> 	at OurApp(OurApp.kt:28) ~[main/:na]
> 	at OurApp.main(OurApp.kt) ~[main/:na]
> Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class org.jodconverter.boot.autoconfigure.JodConverterLocalProperties
> 	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:162) ~[spring-core-5.3.26.jar:5.3.26]
> 	at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:402) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:325) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202) ~[spring-context-5.3.26.jar:5.3.26]
> 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:177) ~[spring-context-5.3.26.jar:5.3.26]
> 	... 14 common frames omitted
> Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.jodconverter.boot.autoconfigure.JodConverterLocalProperties] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@1d44bcfa]
> 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485) ~[spring-core-5.3.26.jar:5.3.26]
> 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:459) ~[spring-core-5.3.26.jar:5.3.26]
> 	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:151) ~[spring-core-5.3.26.jar:5.3.26]
> 	... 19 common frames omitted
> Caused by: java.lang.NoClassDefFoundError: org/jodconverter/local/task/LoadDocumentMode
> 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
> 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
> 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
> 	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467) ~[spring-core-5.3.26.jar:5.3.26]
> 	... 21 common frames omitted
> Caused by: java.lang.ClassNotFoundException: org.jodconverter.local.task.LoadDocumentMode
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
> 	... 25 common frames omitted
> ```
> 
> Мы попробовали добавить jodconverter-local в зависимости от ситуации, но проблема не исчезла. Есть рекомендации?

Good afternoon
Could you provide more code examples? Now I'm trying to set up a similar structure. It is not possible to access the container with libraoffice from the container with the java service.


https://github.com/jodconverter/jodconverter/issues/376
