### ISSUE TITLE
4.4.2word导出pdf，偶尔出现org.jodconverter.core.office.OfficeException: Task did not complete: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, for mat=null}, loadProperties=null, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null}

### ISSUE THREAD

**Issue by yuyongxing** [jodconverter/jodconverter#336]
完整报错信息

**Comment by yuyongxing** [comment]
error:[org.jodconverter.core.office.OfficeException: Task did not complete: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, for
mat=null}, loadProperties=null, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null}
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:104)
	at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:217)
	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:149)
	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:62)
	at com.digov.api.util.file.FormUtil.generateProjectPDF(FormUtil.java:207)
	at com.digov.api.service.yhqq2.business.company.apply.record.ext.impl.Yhqq2BusinessCompanyApplyRecordExtServiceImpl.exportApplication(Yhqq2BusinessCompanyApplyRecordExtServiceImpl.java:223)
	at com.digov.api.service.yhqq2.business.company.apply.record.ext.impl.Yhqq2BusinessCompanyApplyRecordExtServiceImpl$$FastClassBySpringCGLIB$$3d817220.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at com.digov.api.service.yhqq2.business.company.apply.record.ext.impl.Yhqq2BusinessCompanyApplyRecordExtServiceImpl$$EnhancerBySpringCGLIB$$3fbf4b23.exportApplication(<generated>)
	at com.digov.api.controller.yhqq2.business.company.apply.record.ext.Yhqq2BusinessCompanyApplyRecordExtController.exportApplication(Yhqq2BusinessCompanyApplyRecordExtController.java:119)
	at com.digov.api.controller.yhqq2.business.company.apply.record.ext.Yhqq2BusinessCompanyApplyRecordExtController$$FastClassBySpringCGLIB$$26a39e3a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.digov.api.config.aop.AccessLogger.doAround(AccessLogger.java:154)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.digov.api.controller.yhqq2.business.company.apply.record.ext.Yhqq2BusinessCompanyApplyRecordExtController$$EnhancerBySpringCGLIB$$21dd94c3.exportApplication(<generated>)
	at sun.reflect.GeneratedMethodAccessor442.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.knife4j.spring.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.knife4j.spring.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:90)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.digov.api.config.filter.HttpServletRequestFilter.doFilter(HttpServletRequestFilter.java:31)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jodconverter.core.job.DocumentSpecsIOException: Could not write stream to file '/tmp/.jodconverter_25219734-fe6c-4f31-81fd-25f81e841adf/tempfile_78'
	at org.jodconverter.core.job.SourceDocumentSpecsFromInputStream.getFile(SourceDocumentSpecsFromInputStream.java:83)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:108)
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:120)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:80)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.io.FileNotFoundException: /tmp/.jodconverter_25219734-fe6c-4f31-81fd-25f81e841adf/tempfile_78 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.jodconverter.core.job.SourceDocumentSpecsFromInputStream.getFile(SourceDocumentSpecsFromInputStream.java:72)
	... 7 more
]

**Comment by sbraconnier** [comment]
Well, I need a little bit more context here!!  What is your configuration ? How are you converting document ? etc...

The best would be to have a sample project I could work with to reproduce the issue...

**Comment by yuyongxing** [comment]
This issue occurs occasionally, and currently no triggering conditions have been found. However, if the project does not restart after this issue occurs, PDF to Word conversion will continue to fail.

project : centos7 + spring-boot 2.1.9 + jodconverter 4.4.2 + libreoffice7.3
spring boot configuration info:
`jodconverter.local.enabled=true
#libreOffice根目录
jodconverter.local.officeHome=/opt/libreoffice7.3
#任务执行的超时时间
jodconverter.local.taskExecutionTimeout=86400000
#任务队列的超时时间
jodconverter.local.taskQueueTimeout=86400000
#端口（线程）
jodconverter.local.portNumbers[0]=2001
jodconverter.local.portNumbers[1]=2002
jodconverter.local.portNumbers[2]=2003
#一个进程的超时时间
jodconverter.local.processTimeout=86400000`

**Comment by yuyongxing** [comment]
This issue occurs occasionally, and currently no triggering conditions have been found. However, if the project does not restart after this issue occurs, PDF to Word conversion will continue to fail.

**Comment by yuyongxing** [comment]
This issue occurs occasionally, and currently no triggering conditions have been found. However, if the project does not restart after this issue occurs, PDF to Word conversion will continue to fail.
project info: centos7 + libreoffice7.3 + spring  boot 2.1.9 + jodconverter 4.4.2
spring boot configuration info:
jodconverter.local.enabled=true
jodconverter.local.officeHome=/opt/libreoffice7.3
jodconverter.local.taskExecutionTimeout=86400000
jodconverter.local.taskQueueTimeout=86400000
jodconverter.local.portNumbers[0]=2001
jodconverter.local.portNumbers[1]=2002
jodconverter.local.portNumbers[2]=2003
jodconverter.local.processTimeout=86400000

**Comment by yuyongxing** [comment]
word to PDF.

**Comment by yuyongxing** [comment]
I will try it with the default configuration

**Comment by llans250** [comment]
hey guy, I have also encountered the same problem. Do you have any relevant solutions

**Comment by yuyongxing** [comment]
我这边目前没有找到原因，未解决。

**Comment by yuyongxing** [comment]
I haven't found the cause on my end yet and it hasn't been resolved.

**Comment by sbraconnier** [comment]
As ask before, do you have a sample document to provide I could work with that is causing the problem ? I will try to reproduce the issue.

**Comment by uabajwa** [comment]
I am facing same issue. I am using this in a project where Spring boot is there. The project is Spring based cannot use autoconfigure in that so I used the code is custom way. On server startup i am creating the officeManager and on the run when a request to convert word/excel/ppt to pdf i am creating the documentconverter. I am using all default configurations so it works for some time but after let's 2 hours it start throwing the exception. and if i check the path in my Temp folder there is no file there.

I cannot share the project code as its not allowed for me

**Comment by Joycebai666** [comment]
I have encountered a similar problem before, and later found out that it was caused by the Chinese Font (Song typeface) not being installed in the docker image.

**Comment by llans250** [comment]
Hello everyone, perhaps reading this page about the configuration of the workdir directory can solve your confusion

**Comment by llans250** [comment]
> I have encountered a similar problem before, and later found out that it was caused by the Chinese Font (Song typeface) not being installed in the docker image.

https://github.com/jodconverter/jodconverter/wiki/Configuration

**Comment by yuyongxing** [comment]
@sbraconnier After analyzing the issue, I found that it was caused by not configuring jodconverter.local.workingDir. The problem is now fixed. Thanks to you!
