### ISSUE TITLE
Getting error: Unsupported URL  "type detection failed"

### ISSUE THREAD

**Issue by rubyylr** [jodconverter/jodconverter#337]
Hi, I am using jodconverter-4.4.6 with libreoffice7.3 to convert docx to pdf in linux, then I get the error below: 
`org.jodconverter.core.office.OfficeException: Could not open document: 77180527-078e-4e8d-ba9c-0e78768c920c.docx
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:219)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:129)
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.star.lang.IllegalArgumentException: Unsupported URL <file:///home/ygt/ppf/doclib/review/77180527-078e-4e8d-ba9c-0e78768c920c.docx>: "type detection failed"
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at com.sun.proxy.$Proxy74.loadComponentFromURL(Unknown Source)
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocumentFromURL(AbstractLocalOfficeTask.java:240)
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:204)
	... 7 more`

I try the same code in windows, it convert to pdf well, but it's not working in linux environment. Also, I try the libreoffice command to convert the file, that works too. How can I do to let it work in linux?

Here is my code:
` 
	 OfficeManager localOfficeManager = LocalOfficeManager.install(); 
	 localOfficeManager.start(); 
	 LocalConverter converter = LocalConverter.builder().officeManager(localOfficeManager).build(); 
	 converter.convert(new File(inpath)).to(new File(outpath)).execute(); 
	 localOfficeManager.stop();
`

**Comment by sbraconnier** [comment]
You meant that you tried the libreoffice command on linux and it worked ?

**Comment by rubyylr** [comment]
> You meant that you tried the libreoffice command on linux and it worked ?

Problem solved! There is a 5.x version of libreoffice installed on Linux, so I set the correct office home directory , it works now. 
Thanks for the reply : )
