### ISSUE TITLE
 hwp file cannot be opened

### ISSUE THREAD

**Issue by RemixC** [jodconverter/jodconverter#343]
java.lang.NullPointerException: Could not open document: 111.hwp
java.lang.NullPointerException： 无法打开文档： 111.hwp
at org.jodconverter.core.util.AssertUtils.notNull(AssertUtils.java:132) ~[jodconverter-core-4.4.6.jar:4.4.6]
at org.jodconverter.core.util.AssertUtils.notNull（AssertUtils.java：132） ~[jodconverter-core-4.4.6.jar：4.4.6]
at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:210) ~[jodconverter-local-4.4.6.jar:4.4.6]
at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument（AbstractLocalOfficeTask.java：210） ~[jodconverter-local-4.4.6.jar：4.4.6]
at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:129) ~[jodconverter-local-4.4.6.jar:4.4.6]
at org.jodconverter.local.task.LocalConversionTask.execute（LocalConversionTask.java：129） ~[jodconverter-local-4.4.6.jar：4.4.6]
at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121) [jodconverter-local-4.4.6.jar:4.4.6]
at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute（LocalOfficeManagerPoolEntry.java：121） [jodconverter-local-4.4.6.jar：4.4.6]
at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81) [jodconverter-core-4.4.6.jar:4.4.6]
at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0（AbstractOfficeManagerPoolEntry.java：81） [jodconverter-core-4.4.6.jar：4.4.6]

I installed the plugin then libreOffice

**Comment by sbraconnier** [comment]
Maybe you will need to use [this option](https://github.com/jodconverter/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) with libre office plugins ?

Look [here](https://github.com/sbraconnier/jodconverter/issues/41#issuecomment-359625798) for an example on how to set this property.

**Comment by sbraconnier** [comment]
Closing this one. Feel free to  reopen with more details if needed.
