### ISSUE TITLE
Unwanted SSL is triggered

### ISSUE THREAD

**Issue by kemuning** [jodconverter/jodconverter#345]
Hi,

With the following configurations :

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	
	<groupId>xyz.mycomp</groupId>
	<artifactId>api</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	
        <packaging>war</packaging>
	<name>api</name>
	<description> Sample
	</description>
	
	<properties>
		<java.version>17</java.version>
		
		<jodconverter.version>4.4.6</jodconverter.version>		
                <springdocv2.version>2.1.0</springdocv2.version>
		
	</properties>
	
	<dependencies>
	<dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-actuator</artifactId>
	</dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdocv2.version}</version>
        </dependency>
   
	<dependency>
		<groupId>org.projectlombok</groupId>
		<artifactId>lombok</artifactId>
		<optional>true</optional>
	</dependency>
		
	<!-- JODConverter -->
	<dependency>
      		<groupId>org.jodconverter</groupId>
      		<artifactId>jodconverter-local-lo</artifactId>
      		<version>${jodconverter.version}</version>
   	</dependency>
	<dependency>
		<groupId>org.jodconverter</groupId>
		<artifactId>jodconverter-spring-boot-starter</artifactId>
      		<version>${jodconverter.version}</version>
	</dependency>
				
	<!-- Testing -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-test</artifactId>
		<scope>test</scope>
		</dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
		
	</dependencies>
		
	<build>
		<finalName>${project.name}</finalName>
		
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
		
	</build>

</project>
```

JODConverter tried to instantiate the SslConfig :

```
2023-07-24T13:51:40.117+02:00 DEBUG 2868 --- [er-offprocmng-1] o.j.local.office.ExitCodeRetryable       : Execution attempt #1
2023-07-24T13:51:40.117+02:00 DEBUG 2868 --- [er-offprocmng-1] o.j.local.office.ExitCodeRetryable       : Execution attempt #1 failed, retrying after sleep of 250 ms
2023-07-24T13:51:40.180+02:00  INFO 2868 --- [ssageDispatcher] o.j.local.office.OfficeConnection        : Disconnected from 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1'
2023-07-24T13:51:40.379+02:00 DEBUG 2868 --- [er-offprocmng-1] o.j.local.office.ExitCodeRetryable       : Execution attempt #2
2023-07-24T13:51:40.379+02:00 DEBUG 2868 --- [er-offprocmng-1] o.j.local.office.ExitCodeRetryable       : Execution succeeded on attempt #2
2023-07-24T13:51:40.379+02:00  INFO 2868 --- [er-offprocmng-1] o.j.l.office.LocalOfficeProcessManager   : Process exited with code 0
2023-07-24T13:51:40.380+02:00 DEBUG 2868 --- [er-offprocmng-1] o.jodconverter.core.office.OfficeUtils   : Deleting 'C:\Users\ba111\AppData\Local\Temp\.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1'
2023-07-24T13:51:40.380+02:00 DEBUG 2868 --- [er-offprocmng-1] o.j.c.o.OfficeUtils$DeleteFileRetryable  : Execution attempt #1
2023-07-24T13:51:40.442+02:00 DEBUG 2868 --- [er-offprocmng-1] o.j.c.o.OfficeUtils$DeleteFileRetryable  : Execution succeeded on attempt #1
2023-07-24T13:51:40.442+02:00 DEBUG 2868 --- [           main] o.j.l.office.LocalOfficeProcessManager   : Stop task executed successfully.
2023-07-24T13:51:40.442+02:00 DEBUG 2868 --- [           main] o.jodconverter.core.office.OfficeUtils   : Deleting 'C:\Users\ba111\AppData\Local\Temp\.jodconverter_f4a02c16-a1f2-46ae-bbb1-71fa0c79fd1d'
2023-07-24T13:51:40.442+02:00 DEBUG 2868 --- [           main] o.j.c.o.OfficeUtils$DeleteFileRetryable  : Execution attempt #1
2023-07-24T13:51:40.442+02:00 DEBUG 2868 --- [           main] o.j.c.o.OfficeUtils$DeleteFileRetryable  : Execution succeeded on attempt #1
2023-07-24T13:51:40.442+02:00  INFO 2868 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-07-24T13:51:40.481+02:00  INFO 2868 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-07-24T13:51:40.490+02:00 ERROR 2868 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jodconverter.remote-org.jodconverter.boot.autoconfigure.JodConverterRemoteProperties': org/jodconverter/remote/ssl/SslConfig
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:605) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[spring-context-6.0.11.jar:6.0.11]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.11.jar:6.0.11]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.2.jar:3.1.2]
        at fr.anfr.api.ApiApplication.main(ApiApplication.java:10) ~[classes/:na]
Caused by: java.lang.NoClassDefFoundError: org/jodconverter/remote/ssl/SslConfig
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperties.getDeclaredMethods(JavaBeanBinder.java:140) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperties.getSorted(JavaBeanBinder.java:149) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperties.addProperties(JavaBeanBinder.java:132) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperties.<init>(JavaBeanBinder.java:127) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$Bean.<init>(JavaBeanBinder.java:232) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$Bean.get(JavaBeanBinder.java:264) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:58) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:482) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:596) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:582) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:480) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:419) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:348) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$4(Binder.java:478) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:99) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:87) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:63) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:482) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:596) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:582) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:480) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:419) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:348) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:337) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:267) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:254) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:94) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:96) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:79) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.11.jar:6.0.11]
        ... 15 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.jodconverter.remote.ssl.SslConfig
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
        ... 50 common frames omitted
```

which is weird, given my settings in the application.properties :

```
# LOGGING
logging.level.org.jodconverter = debug

# JODConverter
jodconverter.local.enabled = true
jodconverter.remote.enabled = false
jodconverter.remote.ssl.enabled = false
```

Any idea ? Thanks for any help.

**Comment by kemuning** [comment]
This is weird ... it works if you run 'mvn clean spring-boot:run', but if you package into a war then deploy into tomcat, then you got those exception.

It will work in tomcat if you add another dependency :

```
<dependency>
    <groupId>org.jodconverter</groupId>
    <artifactId>jodconverter-remote</artifactId>
    <version>${jodconverter.version}</version>
</dependency>
```

Why would I need to add it if I already defined in my application.properties to disable both remote and ssl ?

**Comment by sbraconnier** [comment]
Well... I think you just need to remove the "remote" properties from your application.properties file. [This](https://github.com/jodconverter/jodconverter-samples/tree/main/samples/spring-boot-rest) spring boot sample project does not use the remote module nor does it appear as dependency.
