### ISSUE TITLE
Error: This office manager is not running.

### ISSUE THREAD

**Issue by Madhupatel08** [jodconverter/jodconverter#353]
hi @sbraconnier !
I'm trying to convert a multi-page text file to multi-page PNG using PageSelector filter. I'm getting following error. what's the possible solution for this. soffice is running in port 8081 in my system. 

thanks!

**Error:** 
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/itcloud/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Exception in thread "main" java.lang.IllegalStateException: This office manager is not running.
	at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:206)
	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:181)
	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:63)
	at org.example.PageFilterMultiPage.main(PageFilterMultiPage.java:33)
Disconnected from the target VM, address: '127.0.0.1:41585', transport: 'socket'
```
**code:-**
```java
public class PageFilterMultiPage {
    public static void main(String[] args) throws OfficeException {
        LocalOfficeManager officeManager = LocalOfficeManager.builder().portNumbers(new int[]{8081}).install().build();
        // OfficeManager officeManager = LocalOfficeManager.builder().
        //       officeHome("/usr/lib/libreoffice").install().build();
        
        File inputFile = new File("rtfFile.txt");
        File outputFile = new File("rtfFile.png");

        DocumentFormatRegistry formatRegistry = DefaultDocumentFormatRegistry.getInstance();

        try {
            for(int i=1;i<=3;i++) {
                LocalConverter converter = LocalConverter.builder().
                        filterChain(new PagesSelectorFilter(i)).build();

                converter.convert(inputFile).to(outputFile).execute();
            }
        } catch (OfficeException e) {
            e.printStackTrace();
        } finally {

            OfficeUtils.stopQuietly(officeManager);
        }
    }
}

```

**Comment by Madhupatel08** [comment]
Hi, 

This issue was resolved for me. I changed the way I make a connection with officeManager, I used following
```java

LocalOfficeManager officeManager = LocalOfficeManager.install();
officeManager.start();
```

**Comment by Madhupatel08** [comment]
Hi, 

This issue was resolved for me. I changed the way I make a connection with officeManager, I used following
```java

LocalOfficeManager officeManager = LocalOfficeManager.install();
officeManager.start();
```

**Comment by Madhupatel08** [comment]
Hi, 

This issue was resolved for me. I changed the way I make a connection with officeManager, I used following
```java

LocalOfficeManager officeManager = LocalOfficeManager.install();
officeManager.start();
```
