### ISSUE TITLE
pptx file conversion of PDF failed

### ISSUE THREAD

**Issue by 260228060** [jodconverter/jodconverter#359]
**version**：LibreOffice 6.1

**invok code：**
```java
public static boolean parseLocation(String docPath,String descExt, Integer timeout) {
    File src = new File(docPath);
    File dst = new File(docPath+"."+descExt);
    OfficeManager officeManager = LocalOfficeManager.builder()
            .taskExecutionTimeout(1000 * 60 * timeout)
            //				.officeHome("/opt/libreoffice6.1/")
            .build();
    try {
        officeManager.start();
        LocalConverter.builder()
                .officeManager(officeManager)
                .build().convert(src).to(dst).execute();
        return true;
    } catch (Exception e) {
        logger.error(e.getMessage(), e);
        return false;
    } finally {
        OfficeUtils.stopQuietly(officeManager);
    }
}
```

**source file：**
[test.pptx](https://github.com/jodconverter/jodconverter/files/13246474/test.pptx)

**thread stack：**
2023-11-03 11:03:16.113  INFO 9 --- [erPoolEntry-607] o.jodconverter.task.LocalConversionTask  : Executing local conversion task...
2023-11-03 11:03:16.494 ERROR 9 --- [ docContainer-1] com.zxy.fastdfs.convert.util.DocUtil     : Task failed

org.jodconverter.office.OfficeException: Task failed
        at org.jodconverter.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:106) ~[jodconverter-core-4.2.0.jar!/:4.2.0]
        at org.jodconverter.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:105) ~[jodconverter-core-4.2.0.jar!/:4.2.0]
        at org.jodconverter.office.LocalOfficeManager.execute(LocalOfficeManager.java:36) ~[jodconverter-local-4.2.0.jar!/:4.2.0]
        at org.jodconverter.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:174) ~[jodconverter-local-4.2.0.jar!/:4.2.0]
        at org.jodconverter.job.AbstractConversionJob.execute(AbstractConversionJob.java:57) ~[jodconverter-core-4.2.0.jar!/:4.2.0]

**Comment by sbraconnier** [comment]
Well... I'm not able to open the attached file with my LibreOffice installation. It crashed everytime.

![LO Screenshot 2023-12-13 081834](https://github.com/jodconverter/jodconverter/assets/15372565/7c36059d-bbef-4ff5-8d03-ef7d732d3d1f)

If you have configured something special and you are able to open the file, you could take a look at [this](https://github.com/jodconverter/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) property. You may also send the file to the LibreOffice team for investigation. This is not a JODConverter issue.
