### ISSUE TITLE
Temp folder not deleted after Timeout Exceptions

### ISSUE THREAD

**Issue by amalianeag** [jodconverter/jodconverter#362]
I am trying to convert an XLSM file to PDF, but it takes more that the configured timeout (DEFAULT_TASK_EXECUTION_TIMEOUT = 120000L). So a TimeoutException is thrown:

`
org.jodconverter.core.office.OfficeException: Task did not complete within timeout: LocalConversionTask{source=SourceDocumentSpecsFromFile{file=ABC.xlsm, format=null}, loadProperties=null, target=TargetDocumentSpecsFromFile{file=ABC_CONVERTED_21.pdf, format=pdf}, storeProperties=null}
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:118)
	at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:217)
	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:149)
	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:62)	
	...
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:88)
	... 29 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:64948', transport: 'socket'

2023-11-29 09:19:27.606 [main] INFO  o.j.c.o.AbstractOfficeManagerPool - Stopping the office manager pool...
2023-11-29 09:19:27.607 [MessageDispatcher] INFO  o.j.local.office.OfficeConnection - Disconnected from 'socket,host=127.0.0.1,port=64951,tcpNoDelay=1'
2023-11-29 09:19:27.610 [MessageDispatcher] WARN  o.j.l.o.LocalOfficeManagerPoolEntry - Connection lost unexpectedly; attempting restart
2023-11-29 09:19:27.610 [main] DEBUG o.j.l.o.LocalOfficeProcessManager - Submitting stop task...
2023-11-29 09:19:27.610 [MessageDispatcher] INFO  o.j.l.o.LocalOfficeProcessManager - Restarting due to lost connection...
...
`

The `AbstractOfficeManagerPoolEntry `catches the TimeoutException and `handleExecuteTimeoutException `:
```

// Is the the task did not complete within the configured timeout, we must restart
officeProcessManager.restartDueToTaskTimeout();
```

`LocalOfficeProcessManager.restartDueToTaskTimeout ` is called and `forciblyTerminateProcess ` by killing the office process instance.

The process is killed, but the temp folder generated is NOT deleted:

![image](https://github.com/jodconverter/jodconverter/assets/28618032/3618bd78-70f9-4957-a6a7-cab346adec5a)

In case of multiple timeouts, the temp folder gets poluted with such temp folders:

![image](https://github.com/jodconverter/jodconverter/assets/28618032/f3009a73-188f-4383-8faa-5d7411cf743b)

Any idea why the temp folders do not get deleted in this case? 
Any help would be appreciated.
Thanks,
Amalia

jodconverter: 4.4.2
LibreOffice: 7.6.3.2

**Comment by sbraconnier** [comment]
Well, I didn't know that. I took a look and I currently have 410 lu*.tmp folders in my temp directory. I didn't know they were related to LibreOffice.

But I also have hundreds of tomcat related directories,  edge, chrome, etc..., so it's not something unique to LibreOffice. The fact that we are killing the process most probably doesn't help! I don't think this is a big issue and there is even some OS that automatically clean this directory.

In also can be done on Windows I think. Take a look at the [Storage Sense](https://support.microsoft.com/en-us/windows/manage-drive-space-with-storage-sense-654f6ada-7bfc-45e5-966b-e24aded96ad5) feature.

**Comment by amalianeag** [comment]
Hello Simon,
thanks for the answer.

Would be nice to have the cleanup automatically done in the library, to avoid extra manual interaction from developers / devops.
JodConverter already does it properly in most of the cases. 
It seems that, in this particular case with TimeoutException, the cleanup is not done properly for some reasons. Would be nice to have this also covered in the library code.

As a workaround, I have currently implemented a cleanup in my code. The LibreOffice temporary files from system temp folder will be deleted if a conversion fails and if they have not yet been deleted by JodConverter library. The LibreOffice temporary files are:
- starting with “`lu`" prefix
- starting with “`OSL_PIPE`" prefix - these are generated only on Linux operating system

But this is not the optimal solution.

**Comment by sbraconnier** [comment]
In order to properly clean this directory, we would have to know for sure which temp dir is created for the LO/OO instance started by jodconverter, which can launch multiple LO/OO instances simultaneously if you configure more than 1 port number. It can also be used while LO/OO is already started the usual way by a user to open a document. We cannot be 100% sure that a directory starting with "lu" is not used anymore.

How do you know for sure in your cleanup that a "lu" directory is not used anymore ?? Are you listing the living processes first ? Or you just assume you have to delete them all because your jodconverter configuration only launch 1 process at the time and that the LO/OO installation is not supposed to be used by another program or by a normal user ??

**Comment by amalianeag** [comment]
I appreciate your input, however I believe the main goal should be to find a solution within the Java library itself.
Given that the library effectively manages temporary folder cleanup in a majority of scenarios, I propose that a similar approach be adopted for addressing TimeoutExceptions.

**Comment by sbraconnier** [comment]
Just to clarify again, jodconverter does not "delete" the directories created by LibreOffice. They are delete by LibreOffice on graceful exit, and they are not when we have to kill the process when it doesn't respond anymore. Jodconverter doesn't know which directory was created by LibreOffice when a process starts.

The best we could do is to list all the LO/OO processes and delete all the directories when there is no process running. It would not be the default behavior tho since some OS already clean the temp directory, but would be activated through a configuration option.

I'll try to introduce this in the next version.
