### ISSUE TITLE
Error when converting Excel to PDF

### ISSUE THREAD

**Issue by kemuning** [jodconverter/jodconverter#366]
Hello,

I got the following error when converting an Excel file :

```
08-01-2024 11:44:02 [http-nio-8080-exec-2][DEBUG] o.j.c.o.AbstractOfficeManagerPool.acquireManager - Acquiring an office manager from the pool...
08-01-2024 11:44:02 [http-nio-8080-exec-2][DEBUG] o.j.c.o.AbstractOfficeManagerPool.acquireManager - Office manager acquired successfully from the pool.
08-01-2024 11:44:02 [http-nio-8080-exec-2][DEBUG] o.j.c.o.AbstractOfficeManagerPoolEntry.waitTaskCompletion - Waiting 120000 ms for task to complete: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null, useStreamAdapters=false}
08-01-2024 11:44:02 [jodconverter-poolentry-1][DEBUG] o.j.l.o.LocalOfficeManagerPoolEntry.doExecute - Executing task: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null, useStreamAdapters=false}
08-01-2024 11:44:02 [jodconverter-poolentry-1][INFO] o.j.l.t.LocalConversionTask.execute - Executing local conversion task [? -> pdf]...
08-01-2024 11:44:02 [jodconverter-poolentry-1][DEBUG] o.j.l.f.PagesSelectorFilter.doFilter - Applying the PagesSelectorFilter for a Calc document
08-01-2024 11:44:02 [jodconverter-poolentry-1][ERROR] o.j.l.t.LocalConversionTask.execute - Local conversion failed.
org.jodconverter.core.office.OfficeException: Could not store document: tempfile_13.pdf
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:198)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:131)
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.sun.star.io.IOException: SfxBaseModel::impl_store <file:///opt/tomcat/temp/.jodconverter_b2b85a12-1b18-42f2-9878-2c5e94ba8bc3/tempfile_13.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16) at /home/buildslave/source/libo-core/sfx2/source/doc/sfxbasemodel.cxx:3215 at /home/buildslave/source/libo-core/sfx2/source/doc/sfxbasemodel.cxx:1789
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:158)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:122)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:312)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:281)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:81)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:619)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:145)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:129)
	at com.sun.proxy.$Proxy128.storeToURL(Unknown Source)
	at org.jodconverter.local.task.LocalConversionTask.storeDocumentToURL(LocalConversionTask.java:214)
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:192)
	... 7 common frames omitted
08-01-2024 11:44:02 [http-nio-8080-exec-2][DEBUG] o.j.c.o.AbstractOfficeManagerPool.releaseManager - Returning office manager to the pool...
```

Here is my config :

- OS             : Rocky Linux release 8.8 (Green Obsidian)
- LO              : LibreOffice_7.5.5.2_Linux_x86-64_rpm
- JOD            : 4.4.6
- Spring Boot : 2.7.18

LO is running as follows :
```
21:14:10 user@node78: ~  # ps -eaf | grep office
tomcat   1629638 1629591  0  2023 ?        00:00:41 /opt/libreoffice7.5/program/soffice.bin --accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nolockcheck --nologo --norestore -env:UserInstallation=file:///opt/tomcat/temp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1
21:14:28 user@node78: ~  #
```

And the directory structure of tomcat is :
```
21:19:05 user@node78: /opt/tomcat  # ll
total 140
drwxr-x---  2 tomcat tomcat  4096 10 août  07:57 bin
-rw-r-----  1 tomcat tomcat 19992  4 juil.  2023 BUILDING.txt
drwx------  3 tomcat tomcat  4096 17 août  11:25 conf
-rw-r-----  1 tomcat tomcat  6210  4 juil.  2023 CONTRIBUTING.md
drwxr-x---  2 tomcat tomcat  4096 10 août  07:57 lib
-rw-r-----  1 tomcat tomcat 57092  4 juil.  2023 LICENSE
drwxr-x---+ 2 tomcat tomcat  4096  8 janv. 11:44 logs
-rw-r-----  1 tomcat tomcat  2333  4 juil.  2023 NOTICE
-rw-r-----  1 tomcat tomcat  3398  4 juil.  2023 README.md
-rw-r-----  1 tomcat tomcat  6901  4 juil.  2023 RELEASE-NOTES
-rw-r-----  1 tomcat tomcat 16505  4 juil.  2023 RUNNING.txt
drwxr-x---  5 tomcat tomcat  4096 20 déc.  17:11 temp
drwxr-x---  8 tomcat tomcat   107 20 déc.  17:11 webapps
drwxr-x---  3 tomcat tomcat    22 10 août  08:00 work
21:19:06 user@node78: /opt/tomcat  #
```

Questions :

- which LO version that is supported with JOD 4.4.6 ?
- any idea what that error means ?

**Comment by sbraconnier** [comment]
This is the [ERRCODE_IO_CANTWRITE](https://docs.libreoffice.org/comphelper/html/errcode_8hxx.html#aaf78afa380f578c79975b2073a33dcf8) error.

I found some references about this particular error [here](https://ask.libreoffice.org/t/libreoffice-7-4-convert-docx-txt-to-pdf-error/81532) and [here](https://bugs.documentfoundation.org/show_bug.cgi?id=150846).

Are you able to successfully convert the document using the LibreOffice [command line](https://help.libreoffice.org/latest/en-US/text/shared/guide/start_parameters.html) using the `--convert-to` argument? (without jodconverter).

**Comment by kemuning** [comment]
Using the following command line :
```
10:49:05 user@node78: ~  # /opt/libreoffice7.5/program/soffice.bin --headless --convert-to pdf:calc_pdf_Export --outdir . MAM.xlsx
convert /home/user/MAM.xlsx -> /home/user/MAM.pdf using filter : calc_pdf_Export
```

I have no problem.

So, I just upgraded my jodconverter to 4.4.7, stop tomcat, and start tomcat, and it worked now.
Very strange.

**Comment by sbraconnier** [comment]
Hmm indeed! Maybe it was related to write access or something... ?
