### ISSUE TITLE
LocalOfficeManager not killing existing process on the same port

### ISSUE THREAD

**Issue by blackhumors** [jodconverter/jodconverter#373]
I'm having issues with the killExistingProcess method in LocalOfficeManager. My setup is as follows:

officeManager = LocalOfficeManager.builder()
.install()
.officeHome("/opt/libreoffice6.4")
.processTimeout(60 * 60000)
.taskExecutionTimeout(60 * 60000)
.taskQueueTimeout(24 * 60 * 60000)
.portNumbers(2002)
.processRetryInterval(5000)
.maxTasksPerProcess(2000)
.killExistingProcess(true)
.build();

Even though I set killExistingProcess to true, if port 2002 is already used by a running libreoffice instance, the library throws an error. I was in the impression that killExistingProcess(true) would kill the existing process and allow for a new officeManager instance to be created. But this does not appear to be what's happening.

In cases where the service reboots but the libreoffice process does not end, this leads to an inability to instantiate officeManager. How should I resolve this issue? Any help or guidance would be appreciated. Thanks.

**Comment by blackhumors** [comment]
> And what would be the error that is thrown ?? Do you have a log file (with log level set to DEBUG if possible) showing the start process steps ?

Not every time the service is restarted, the libreoffice process is not terminated. Therefore, I can only simulate this scenario by repeatedly executing the following code twice. The specific code and exception are as follows：
```
officeManager = LocalOfficeManager.builder()
                        .install()
                        .officeHome("/opt/libreoffice6.4")
                        .processTimeout(60 * 60000)
                        .taskExecutionTimeout(60 * 60000)
                        .taskQueueTimeout(24 * 60 * 60000)
                        .portNumbers(2002, 2003, 2004, 2005, 2006)
                        .processRetryInterval(5000)
                        .maxTasksPerProcess(2000)
                        .killExistingProcess(false)
                        .build();
officeManager.start();
```

Exception in thread "main" org.jodconverter.office.OfficeException: A process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' is already running; pid 200888
	at org.jodconverter.office.OfficeProcess.checkForExistingProcess(OfficeProcess.java:106)
	at org.jodconverter.office.OfficeProcess.start(OfficeProcess.java:381)
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:100)
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:261)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:256)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sbraconnier** [comment]
You seem to be using a very old version of jodconverter. The OfficeProcess class has been replaced in the 4.3.0 version of jodconverter, which was release 4 years ago.

Can you try with the latest version of jodconverter?

**Comment by blackhumors** [comment]
officeManager = LocalOfficeManager.builder()
        .install()
        .officeHome("/opt/libreoffice6.4")
        .processTimeout(60 * 60000L)
        .taskExecutionTimeout(60 * 60000L)
        .taskQueueTimeout(24 * 60 * 60000L)
        .portNumbers(2002, 2003, 2004, 2005, 2006)
        .processRetryInterval(5000L)
        .maxTasksPerProcess(2000)
        .existingProcessAction(ExistingProcessAction.CONNECT_OR_KILL)
        .build();

I tried with the latest version, change the method to existingProcessAction, It works. Thanks!
