### ISSUE TITLE
Scanner bug

### ISSUE THREAD

**Issue by Osiris-Team** [jodconverter/jodconverter#383]
Having a Scanner on System.in in another thread breaks jodconverter, to reproduce do something like this:

<details>
<summary>Code</summary>

```java
package com.osiris.danielmanager.utils;

import org.jodconverter.core.document.DefaultDocumentFormatRegistry;
import org.jodconverter.core.document.DocumentFamily;
import org.jodconverter.core.document.DocumentFormat;
import org.jodconverter.core.document.DocumentFormatRegistry;
import org.jodconverter.core.office.OfficeException;
import org.jodconverter.local.LocalConverter;
import org.jodconverter.local.filter.PagesSelectorFilter;
import org.jodconverter.local.office.LocalOfficeManager;

import java.io.*;
import java.nio.file.Files;
import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;

public class Office {

    // Create an office manager using the default configuration.
    // The default port is 2002. Note that when an office manager
    // is installed, it will be the one used by default when
    // a converter is created.
    final public static File workingDir = new File(System.getProperty("user.dir") + "/office");
    public static LocalOfficeManager officeManager;
    public static Set<DocumentFormat> formats = new HashSet<>();

    static {
        final DocumentFormatRegistry ref = DefaultDocumentFormatRegistry.getInstance();
        formats.addAll(ref.getOutputFormats(DocumentFamily.TEXT));
        //logSupportedGroupFormats("Supported Text Document Formats are:", formats);
        formats.addAll(ref.getOutputFormats(DocumentFamily.SPREADSHEET));
        //logSupportedGroupFormats("Supported SpreadSheet Document Formats are:", formats);
        formats.addAll(ref.getOutputFormats(DocumentFamily.PRESENTATION));
        //logSupportedGroupFormats("Supported Presentation Document Formats are:", formats);
        formats.addAll(ref.getOutputFormats(DocumentFamily.DRAWING));
    }

    public static void main(String[] args) throws IOException, OfficeException {
        // This works fine
        initConverter();
        convertDocuments();
        new ConsoleInputThread().start();
        // This fails by timeouting:
        //new ConsoleInputThread().start();
        //initConverter();
        //convertDocuments();
    }

    public static void initConverter() {
        // Start an office process and connect to the started instance (on port 2002).
        try {
            workingDir.mkdirs();
            officeManager = LocalOfficeManager.builder().install().workingDir(workingDir).build();
            officeManager.start();
            System.out.println("OfficeManager init -> " + officeManager);
            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                try {
                    officeManager.stop();
                } catch (OfficeException e) {
                    e.printStackTrace();
                }
            }));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void convertDocuments() throws OfficeException, IOException {
        for (int i = 0; i < 20; i++) {
            File pdf = new File(System.getProperty("user.dir") + "/test.odt");
            byte[] data = createWordDocxPreview(new FileInputStream(pdf), DefaultDocumentFormatRegistry.ODT);
            File png = new File(System.getProperty("user.dir") + "/test.png");
            png.delete();
            png.createNewFile();
            Files.write(png.toPath(), data);
        }
    }

    /**
     * @param inputFile  document.docx
     * @param fileFormat
     * @return document.png preview image bytes.
     */
    public static synchronized byte[] createWordDocxPreview(InputStream inputFile, DocumentFormat fileFormat) throws OfficeException {
        if (fileFormat == DefaultDocumentFormatRegistry.PNG) throw new RuntimeException("Already a .png file!");

        final ByteArrayOutputStream outputFile = new ByteArrayOutputStream();

        // Create a page selector filter in order to
        // convert only the first page.
        final PagesSelectorFilter selectorFilter = new PagesSelectorFilter(1);

        LocalConverter
                .builder()
                .filterChain(selectorFilter)
                .build()
                .convert(inputFile)
                .as(fileFormat)
                .to(outputFile)
                .as(DefaultDocumentFormatRegistry.PNG)
                .execute();
        return outputFile.toByteArray();
    }

    /**
     * @param fileExtension like .odt for example.
     * @return true if supported format
     */
    public static DocumentFormat getFormatForFileExtension(String fileExtension) {
        fileExtension = fileExtension.replaceAll("\\.", "");
        for (DocumentFormat format : formats) {
            for (String extension : format.getExtensions()) {
                if (extension.equals(fileExtension)) return format;
            }
        }
        return null;
    }

    /**
     * @param fileExtension like .odt for example.
     * @return true if supported format
     */
    public static boolean isSupported(String fileExtension) {
        return getFormatForFileExtension(fileExtension) != null;
    }

    public static class ConsoleInputThread extends Thread {
        @Override
        public void run() {
            try {
                Scanner scanner = new Scanner(System.in);
                System.out.println(this.getName() + " started. Enter 'help' or '?' for all commands.");
                while (true) {
                    String l = scanner.nextLine();
                    if (l.contains("help") || l.contains("?")) {
                        System.out.println("Commands:");
                        System.out.println("stop/exit | Stops the application gracefully.");
                        System.out.println("add admin <email> <password> | Creates a new admin account.");
                        System.out.println("make admin <email> | Makes an existing account admin.");
                    }
                    // ...
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}


```
</details>

<details>
<summary>Log</summary>

```sh
Thread-0 started. Enter 'help' or '?' for all commands.
2024-05-20 14:39:26.085 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeDescriptor - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
2024-05-20 14:39:26.173 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir 'D:\Coding\JAVA\daniel_manager\office\.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
Entity: line 1: parser error : Document is empty

^
2024-05-20 14:39:30.644 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2024-05-20 14:39:30.645 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Started process; pid: 14908
2024-05-20 14:39:30.646 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:41:26.174 [main] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Restarting due to task timeout...
2024-05-20 14:41:26.174 [main] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Trying to forcibly terminate process: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager'; pid: 14908
Exception in thread "main" org.jodconverter.core.office.OfficeException: Task did not complete within timeout (120000 ms): LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=odt}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=png}, storeProperties=null, useStreamAdapters=false}
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.waitTaskCompletion(AbstractOfficeManagerPoolEntry.java:120)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:86)
	at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:216)
	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:188)
	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:63)
	at com.osiris.danielmanager.utils.Office.createWordDocxPreview(Office.java:81)
	at com.osiris.danielmanager.utils.Office.main(Office.java:27)
	at com.osiris.danielmanager.Application.main(Application.java:35)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.waitTaskCompletion(AbstractOfficeManagerPoolEntry.java:95)
	... 7 more
2024-05-20 14:41:26.277 [MessageDispatcher] INFO org.jodconverter.local.office.OfficeConnection - Disconnected from 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2024-05-20 14:41:26.277 [MessageDispatcher] WARN org.jodconverter.local.office.LocalOfficeManagerPoolEntry - Connection lost unexpectedly; attempting restart
2024-05-20 14:41:26.277 [MessageDispatcher] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Restarting due to lost connection...
2024-05-20 14:41:26.277 [jodconverter-poolentry-1] ERROR org.jodconverter.local.task.LocalConversionTask - Local conversion failed.
com.sun.star.lang.DisposedException
	at com.sun.star.lib.uno.environments.remote.JobQueue.removeJob(JobQueue.java:210)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:330)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at jdk.proxy2/jdk.proxy2.$Proxy8.loadComponentFromURL(Unknown Source)
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocumentFromURL(AbstractLocalOfficeTask.java:240)
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:204)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:129)
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: com.sun.star.io.IOException: java.net.SocketException: Connection reset
	at com.sun.star.lib.uno.bridges.java_remote.XConnectionInputStream_Adapter.read(XConnectionInputStream_Adapter.java:70)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:208)
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:385)
	at com.sun.star.lib.uno.protocols.urp.urp.readBlock(urp.java:355)
	at com.sun.star.lib.uno.protocols.urp.urp.readMessage(urp.java:92)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge$MessageDispatcher.run(java_remote_bridge.java:105)
2024-05-20 14:41:26.277 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Process exited with code 1
2024-05-20 14:41:26.292 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeDescriptor - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
2024-05-20 14:41:26.375 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir 'D:\Coding\JAVA\daniel_manager\office\.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
Entity: line 1: parser error : Document is empty

^
2024-05-20 14:41:30.673 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2024-05-20 14:41:30.673 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Started process; pid: 5176
// etc...
```
</details>

<details>
<summary>Log (if before console input thread init)</summary>

```sh
2024-05-20 14:44:34.111 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeDescriptor - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
2024-05-20 14:44:34.232 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir 'D:\Coding\JAVA\daniel_manager\office\.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
Entity: line 1: parser error : Document is empty

^
2024-05-20 14:44:38.691 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2024-05-20 14:44:38.691 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Started process; pid: 5836
2024-05-20 14:44:38.692 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:40.554 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:40.685 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:40.816 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:40.932 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:41.055 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:41.173 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:41.299 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:41.422 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:41.556 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:41.660 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:41.768 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:41.860 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:41.960 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:42.077 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:42.193 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:42.302 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:42.438 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:42.555 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-05-20 14:44:42.725 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
```
</details>

I have OpenOffice and LibreOffice installed.
Not sure why it uses LibreOffice, even though I am using the default jodconverter version which should only work with OpenOffice as I understood. Just to be sure, I tried out jodconverter-local-lo too, same results.

**Comment by Osiris-Team** [comment]
@sbraconnier any ideas why, or how to fix this?

**Comment by sbraconnier** [comment]
Sorry for the long delay. It's difficult these days for me to find time to work on jodconverter. If you have both OpenOffice and LibreOffice installed, [it will always use LibreOffice first](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeUtils.java#L71), since it's a more active project. Using ` jodconverter-local-lo` or `jodconverter-local-oo` will only change the dependencies used with jodconverter (`org.openoffice` or `org.libreoffice` artifacts). On some OS, it's better to enforce which dependencies we are using. It's not easy to provide a project that support both LibreOffice and OpenOffice with a set of dependencies that evolves at different speeds.

As for your problem, thanks to have report this. I'll ltry to find a way to fix it. I'll keep you posted...

**Comment by Osiris-Team** [comment]
Hey, no worries, its always good when there is at least an answer ;)

**Comment by Osiris-Team** [comment]
@sbraconnier do you maybe have any ideas where the issue could lie in / in which files?
Wouldn't mind creating a PR for this.

**Comment by Osiris-Team** [comment]
@sbraconnier weirdly enough now it fails to save some generated temp file:
```sh
OfficeManager init -> org.jodconverter.local.office.LocalOfficeManager@72b6cbcc
2024-07-04 18:29:07.056 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeDescriptor - soffice info (from exec path): Product: OpenOffice - Version: ??? - useLongOptionNameGnuStyle: false
2024-07-04 18:29:07.182 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir 'D:\Coding\JAVA\daniel_manager\office\.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
2024-07-04 18:29:13.972 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2024-07-04 18:29:13.972 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Started process; pid: 27996
2024-07-04 18:29:13.973 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [odt -> png]...
2024-07-04 18:29:14.197 [jodconverter-poolentry-1] ERROR org.jodconverter.local.task.LocalConversionTask - Local conversion failed.
org.jodconverter.core.office.OfficeException: Could not store document: tempfile_2.png; errorCode: 2074
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:195)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:131)
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.sun.star.task.ErrorCodeIOException: 
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at jdk.proxy2/jdk.proxy2.$Proxy24.storeToURL(Unknown Source)
	at org.jodconverter.local.task.LocalConversionTask.storeDocumentToURL(LocalConversionTask.java:214)
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:192)
	... 7 more
Exception in thread "main" org.jodconverter.core.office.OfficeException: Could not store document: tempfile_2.png; errorCode: 2074
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:195)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:131)
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.sun.star.task.ErrorCodeIOException: 
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at jdk.proxy2/jdk.proxy2.$Proxy24.storeToURL(Unknown Source)
	at org.jodconverter.local.task.LocalConversionTask.storeDocumentToURL(LocalConversionTask.java:214)
	at org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:192)
	... 7 more
2024-07-04 18:29:14.208 [Thread-4] INFO org.jodconverter.core.office.AbstractOfficeManagerPool - Stopping the office manager pool...
2024-07-04 18:29:14.217 [MessageDispatcher] INFO org.jodconverter.local.office.OfficeConnection - Disconnected from 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
2024-07-04 18:29:14.465 [jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Process exited with code 0

```

**Comment by Osiris-Team** [comment]
This is with only OpenOffice (Apache_OpenOffice_4.1.15_Win_x86_install_de.exe) installed globally on my machine and 
```xml
        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-local</artifactId>
            <version>4.4.8-SNAPSHOT</version>
        </dependency>
```

**Comment by Osiris-Team** [comment]
@sbraconnier just installed libreoffice again and now it works even if we are listening to system.in before init!
Great thank you!
