### ISSUE TITLE
Incompatible with LO 24.x (probably?)

### ISSUE THREAD

**Issue by EugenMayer** [jodconverter/jodconverter#386]
When running libreoffice [24.2.3](https://download.documentfoundation.org/libreoffice/stable/24.2.3/deb/x86_64/) with jodconverter 4.4.7 i get an exception on start with

```
2024-06-03T06:52:29.941Z  INFO 4829 --- [Converter] [           main] d.k.c.ConverterApplication$Companion     : Starting ConverterApplication.Companion v1.5.1 using Java 17.0.10 with PID 4829 (/opt/app/officeconverter.jar started by www-data in /)
2024-06-03T06:52:29.952Z  INFO 4829 --- [Converter] [           main] d.k.c.ConverterApplication$Companion     : No active profile set, falling back to 1 default profile: "default"
2024-06-03T06:52:30.454Z  INFO 4829 --- [Converter] [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat initialized with port 8080 (http)
2024-06-03T06:52:30.461Z  INFO 4829 --- [Converter] [           main] o.a.c.c.StandardService                  : Starting service [Tomcat]
2024-06-03T06:52:30.462Z  INFO 4829 --- [Converter] [           main] o.a.c.c.StandardEngine                   : Starting Servlet engine: [Apache Tomcat/10.1.19]
2024-06-03T06:52:30.483Z  INFO 4829 --- [Converter] [           main] o.a.c.c.C.[.[.[/]                        : Initializing Spring embedded WebApplicationContext
2024-06-03T06:52:30.484Z  INFO 4829 --- [Converter] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 473 ms
2024-06-03T06:52:30.693Z  WARN 4829 --- [Converter] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'conversionController' defined in URL [jar:nested:/opt/app/officeconverter.jar/!BOOT-INF/classes/!/de/kontextwork/converter/module/convert/controller/ConversionController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'converterService' defined in URL [jar:nested:/opt/app/officeconverter.jar/!BOOT-INF/classes/!/de/kontextwork/converter/module/convert/ConverterService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Failed to instantiate [org.jodconverter.core.office.OfficeManager]: Factory method 'localOfficeManager' threw exception with message: officeHome must not be null
2024-06-03T06:52:30.695Z  INFO 4829 --- [Converter] [           main] o.a.c.c.StandardService                  : Stopping service [Tomcat]
2024-06-03T06:52:30.702Z  INFO 4829 --- [Converter] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-06-03T06:52:30.712Z ERROR 4829 --- [Converter] [           main] o.s.b.SpringApplication                  : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'conversionController' defined in URL [jar:nested:/opt/app/officeconverter.jar/!BOOT-INF/classes/!/de/kontextwork/converter/module/convert/controller/ConversionController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'converterService' defined in URL [jar:nested:/opt/app/officeconverter.jar/!BOOT-INF/classes/!/de/kontextwork/converter/module/convert/ConverterService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'localOfficeManager' defined in class path resource [org/jodconverter/boot/autoconfigure/JodConverterLocalAutoConfiguration.class]: Failed to instantiate [org.jodconverter.core.office.OfficeManager]: Factory method 'localOfficeManager' threw exception with message: officeHome must not be null
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.1.4.jar!/:6.1.4]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.4.jar!/:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.4.jar!/:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1192) ~[spring-beans-6.1.4.jar!/:6.1.4]

```

In fact i'am not setting officeHome https://github.com/EugenMayer/officeconverter/blob/main/src/main/kotlin/de/kontextwork/converter/module/convert/ConverterService.kt#L26

My question is, if we expect this to be auto-configured (which i assume) since the asset in org.jodconverter.local.office.LocalOfficeUtils.validateOfficeHome will be there when running LO 7.x there anyway. Any ideas what is needed?

Maybe i'am looking at a false positive? What i did is, i used the jodconverter runtime, uninstalled the install LO 7.x and installed 24 via the LO deb source [24.2.3](https://download.documentfoundation.org/libreoffice/stable/24.2.3/deb/x86_64/)

**Comment by EugenMayer** [comment]
Assuming that `LocalOfficeUtils.getDefaultOfficeHome();` does not yield the right result due to  https://github.com/jodconverter/jodconverter/blob/d2657236ac943edcb3c5f8f4d124ba9031524050/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeUtils.java#L126 not including `/opt/libreoffice24.2` which seems to be home folder with the current debian packages.

Symlinking it via `ln -s /opt/libreoffice24.2/ /opt/libreoffice` does indeed fix the startup issue.

Should i provide a PR to add this folder or are we going to rely on this symlink to simplify the code? Assuming those are the official libreoffice debian packages, this really can become a support-source / issue source in the future. What do you think @sbraconnier ?

For the motivation: 24 does fix a ton of issues with word/pdf conversion.

**Comment by sbraconnier** [comment]
Sorry for the long delay! I'm having trouble to find time to work on jodconverter these days!

I'll add the `/opt/libreoffice24.2` as a potential lo home folder on *nix os.

@EugenMayer Is this folder enough? Or should I also add
```
- /usr/lib64/libreoffice24.2
- /usr/lib/libreoffice24.2
- /usr/local/lib64/libreoffice24.2
- /usr/local/lib/libreoffice24.2
```

**Comment by EugenMayer** [comment]
no worries

@sbraconnier i guess so - in the end, i guess  it is not a lot of maintenance on jodconverter side and it is 'more suitable' for out of the box ops.

Should i make a PR? (or you just quickly commit it)

**Comment by sbraconnier** [comment]
I'll take care of it, I'm already working on something so I'll just take 2 seconds to.... oh... already done 😝!!

**Comment by EugenMayer** [comment]
i guess, we close this one then :D 

Thanks!
