### ISSUE TITLE
Why Task was cancelled

### ISSUE THREAD

**Issue by hartioun** [jodconverter/jodconverter#395]
The exception is like this:

```
Jul 12, 2024 @ 14:18:46.154Caused by: org.jodconverter.core.office.OfficeException: Task was cancelled: LocalConversionTask{source=SourceDocumentSpecsFromInputStream{file=null, format=null}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromOutputStream{file=null, format=pdf}, storeProperties=null, useStreamAdapters=false}
Jul 12, 2024 @ 14:18:46.154	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.waitTaskCompletion(AbstractOfficeManagerPoolEntry.java:101)
Jul 12, 2024 @ 14:18:46.154	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:86)
Jul 12, 2024 @ 14:18:46.154	at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:216)
Jul 12, 2024 @ 14:18:46.154	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:181)
Jul 12, 2024 @ 14:18:46.154	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:63)
```

I noticed that this only happens when multiple users request a conversion at the same time. When the users requests are made separately, it is converted correctly. Below is my code:

```
public static String ConvertToPDF(final String fileInStringBase64) {
        String pdfInBase64 = null;
        LocalOfficeManager officeManager = null;

        try {
            officeManager = LocalOfficeManager.builder().officeHome(LIBRE_OFFICE_PATH).install().build();
            officeManager.start();

            byte[] inputBytes = Base64.getDecoder().decode(fileInStringBase64);
            ByteArrayInputStream input = new ByteArrayInputStream(inputBytes);

            ByteArrayOutputStream outputValidatedRtf = new ByteArrayOutputStream();
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            JodConverter.convert(input).to(outputValidatedRtf).as(DefaultDocumentFormatRegistry.DOC).execute();

            ByteArrayInputStream inputValidatedRtf = new ByteArrayInputStream(outputValidatedRtf.toByteArray());
            JodConverter.convert(inputValidatedRtf).to(output).as(DefaultDocumentFormatRegistry.PDF).execute();

            pdfInBase64 = Base64.getEncoder().encodeToString(output.toByteArray());

        } catch (Exception oe) {
            throw new Exception(oe.getMessage(), oe);
        } finally {
            OfficeUtils.stopQuietly(officeManager);
        }
        return pdfInBase64 ;
    }
```

**Comment by hartioun** [comment]
@sbraconnier Hello Simon, you might have any information on this?
Thanks

**Comment by sbraconnier** [comment]
Hmmm are you calling this function each time you need to convert a document? If yes, that is not what you are suppose to use this library. Starting an office manage starts libre office and creates a connection to the started instance, which is extremely slow.

You should start your office manager when your application starts, and close it when your application ends. You should use this library in a similar way that you would use a database connection pool (instead here we are talking about libre office connection instead of database connection).

**Comment by hartioun** [comment]
Thanks for your reply. 

I am using a Spring Boot application API and this method is called from an endpoint. How should I manage the manager?

Many users or requests call this method simultaneously. How should I control the number of ports to use, since the number of users that will connect in parallel is not known?

Thank you very much!

**Comment by sbraconnier** [comment]
You have a complete example [here](https://github.com/jodconverter/jodconverter-samples/tree/main/samples/spring-boot-rest) of a spring boot rest app.

As for the number of ports, it really depends of your traffic and type of document (a big document takes longer to convert than a small document). A conversion request won't necessarily fail if a conversion is already running. It will wait for an office instance to be available (until the [task queue timeout](https://github.com/jodconverter/jodconverter/wiki/Configuration#watchtaskqueuetimeout) is reached). You could probably starts with 2 ports and see if it is enough for your needs. If you think you'll have hundreds of conversion requests per minute, then maybe use 5 to 10 ports...

**Comment by hartioun** [comment]
Do you  have an example of how you configure multiple ports?

Thanks!

**Comment by sbraconnier** [comment]
The spring boot rest example is configured to use 2 ports. See the application.yml [here](https://github.com/jodconverter/jodconverter-samples/blob/main/samples/spring-boot-rest/src/main/resources/application.yml)

**Comment by sbraconnier** [comment]
I'm closing this one, feel free to re-open if needed
