### ISSUE TITLE
"API misuse: modification of a menu's items on a non-main thread when the menu is part of the main menu." on MacOS

### ISSUE THREAD

**Issue by awidesky** [jodconverter/jodconverter#403]
When I try to convert [this](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.cte.iup.edu/cte/Resources/DOCX_TestPage.docx&ved=2ahUKEwj8o4nwlduHAxXwnq8BHbS1BIwQFnoECBcQAQ&usg=AOvVaw2EIQnuh43y7TAPGBaVQZOd) particular docx file(a test docx file from Indiana University of Pennsylvania)  to pdf in my mac, jodconverter fails with error :
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'API misuse: modification of a menu's items on a non-main thread when the menu is part of the main menu. Main menu contents may only be modified from the main thread.'`
But somehow output pdf file is produced.

I have clean installation of LibreOffice 24.2.5.2 from brew that can open/edit the very docx file with no problem,
and `soffice --headless --convert-to pdf DOCX_TestPage.docx` command on shell successfully converts without error.
I do not get that error if I try to convert other document files.
Is it a bug, or a problem with the docx file?
Initially I suspected the latter, but now I think it might be the former since `soffice` command works just fine on the very docx file.

I used jodconverter-local-lo 4.4.7, and following is the test code and my error output.
```
OfficeManager officeManager;
DocumentConverter converter;
officeManager = LocalOfficeManager.builder().build();
converter = LocalConverter.builder().officeManager(officeManager).build();
officeManager.start();
converter.convert(new File("DOCX_TestPage.docx"))
.to(new File("DOCX_TestPage.pdf"))
.execute();
officeManager.stop();
```

Full error log :
```
[jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeDescriptor - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
[jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeDescriptor - soffice info (from help output): Product: LibreOffice - Version: 24.2.5.2 - useLongOptionNameGnuStyle: true
[jodconverter-offprocmng-0] WARN org.jodconverter.local.office.LocalOfficeProcessManager - Profile dir '/var/folders/01/g5tj8st116b53kmcrp7bcrzm0000gn/T/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1' already exists; deleting
[jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/var/folders/01/g5tj8st116b53kmcrp7bcrzm0000gn/T/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
2024-08-04 20:13:37.605 soffice[85428:3160218] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
2024-08-04 20:13:38.690 soffice[85428:3160270] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
[jodconverter-offprocmng-0] INFO org.jodconverter.local.office.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
[jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Started process; pid: 85428
[jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [docx -> pdf]...
2024-08-04 20:13:41.618 soffice[85428:3160360] *** Assertion failure in -[SalNSMainMenu _lockForMainMenuItemArray], NSMenu.m:1117
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'API misuse: modification of a menu's items on a non-main thread when the menu is part of the main menu. Main menu contents may only be modified from the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018c68f2ec __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x000000018c176788 objc_exception_throw + 60
	2   Foundation                          0x000000018d80242c -[NSCalendarDate initWithCoder:] + 0
	3   AppKit                              0x000000018fe81158 -[NSMenu removeItemAtIndex:] + 128
	4   libvcllo.dylib                      0x0000000106eec324 _ZN4Menu7disposeEv + 452
	5   libtklo.dylib                       0x0000000104e06158 _ZN8VCLXMenuD2Ev + 196
	6   libtklo.dylib                       0x0000000104e0a440 _ZThn32_N11VCLXMenuBarD0Ev + 16
	7   libfwklo.dylib                      0x00000001037fb0e4 _ZN9framework14MenuBarWrapper7disposeEv + 212
	8   libfwklo.dylib                      0x000000010373fa70 _ZN9framework13LayoutManager19impl_clearUpMenuBarEv + 564
	9   libfwklo.dylib                      0x000000010374105c _ZN9framework13LayoutManager22implts_destroyElementsEv + 116
	10  libfwklo.dylib                      0x00000001037406a4 _ZN9framework13LayoutManager12implts_resetEb + 2576
	11  libfwklo.dylib                      0x0000000103791e00 _ZN12_GLOBAL__N_110XFrameImpl27implts_sendFrameActionEventERKN3com3sun4star5frame11FrameActionE + 272
	12  libfwklo.dylib                      0x0000000103789c1c _ZN12_GLOBAL__N_110XFrameImpl12setComponentERKN3com3sun4star3uno9ReferenceINS3_3awt7XWindowEEERKNS5_INS3_5frame11XControllerEEE + 304
	13  libfwklo.dylib                      0x000000010378c1c8 _ZN12_GLOBAL__N_110XFrameImpl5closeEh + 340
	14  libsfxlo.dylib                      0x0000000104363afc _ZN8SfxFrame7DoCloseEv + 220
	15  libsvllo.dylib                      0x0000000104713c94 _ZN14SfxBroadcaster9BroadcastERK7SfxHint + 100
	16  libsfxlo.dylib                      0x00000001042cc9b0 _ZThn40_N12_GLOBAL__N_121SfxModelListener_Impl13notifyClosingERKN3com3sun4star4lang11EventObjectE + 96
	17  libsfxlo.dylib                      0x00000001042e0af0 _ZN12SfxBaseModel5closeEh + 620
	18  libswlo.dylib                       0x000000042b5cfeac _ZN15SwXTextDocument5closeEh + 364
	19  libgcc3_uno.dylib                   0x00000001025270fc _Z19callVirtualFunctionmPmS_S_iPv + 188
	20  libgcc3_uno.dylib                   0x000000010252a1f4 _ZN12_GLOBAL__N_14callEPN7bridges7cpp_uno6shared17UnoInterfaceProxyENS2_10VtableSlotEP33_typelib_TypeDescriptionReferenceiP24_typelib_MethodParameterPvPSA_PP8_uno_Any + 2036
	21  libgcc3_uno.dylib                   0x00000001025299cc unoInterfaceProxyDispatch + 616
	22  libbinaryurplo.dylib                0x0000000106b55f18 _ZNK9binaryurp15IncomingRequest13execute_throwEPNS_9BinaryAnyEPNSt3__16vectorIS1_NS3_9allocatorIS1_EEEE + 1052
	23  libbinaryurplo.dylib                0x0000000106b55708 _ZNK9binaryurp15IncomingRequest7executeEv + 128
	24  libbinaryurplo.dylib                0x0000000106b5ba64 request + 44
	25  libuno_cppu.dylib.3                 0x00000001026af398 _ZN15cppu_threadpool8JobQueue5enterEPKvb + 220
	26  libuno_cppu.dylib.3                 0x00000001026b1ca8 _ZN15cppu_threadpool14ORequestThread3runEv + 144
	27  libuno_cppu.dylib.3                 0x00000001026b1e74 threadFunc + 28
	28  libuno_sal.dylib.3                  0x000000010266469c _ZL21osl_thread_start_ImplPv + 128
	29  libsystem_pthread.dylib             0x000000018c53af94 _pthread_start + 136
	30  libsystem_pthread.dylib             0x000000018c535d34 thread_start + 8
)
libc++abi: terminating due to uncaught exception of type NSException
Unspecified Application Error


Fatal exception: Signal 6
Stack:
0   libuno_sal.dylib.3                  0x0000000102661720 _ZN12_GLOBAL__N_110printStackEi + 52
1   libuno_sal.dylib.3                  0x000000010266c994 _ZN12_GLOBAL__N_121signalHandlerFunctionEiP9__siginfoPv.cold.1 + 24
2   libuno_sal.dylib.3                  0x00000001026615ec _Z14onDeInitSignalv + 0
3   libsystem_platform.dylib            0x000000018c56b584 _sigtramp + 56
4   libsystem_pthread.dylib             0x000000018c53ac20 pthread_kill + 288
5   libsystem_c.dylib                   0x000000018c447a30 abort + 180
6   libvcllo.dylib                      0x00000001071e3dc8 _Z8SalAbortRKN3rtl8OUStringEb + 120
7   libvcllo.dylib                      0x000000010722a680 _ZN11Application5AbortERKN3rtl8OUStringE + 180
8   libsofficeapp.dylib                 0x000000010280c7cc _ZN7desktop7Desktop9ExceptionE17ExceptionCategory + 180
9   libvcllo.dylib                      0x0000000107233484 _ZL23VCLExceptionSignal_implPvP13oslSignalInfo + 316
10  libuno_sal.dylib.3                  0x000000010263493c _Z17callSignalHandlerP13oslSignalInfo + 40
11  libuno_sal.dylib.3                  0x0000000102661264 _ZN12_GLOBAL__N_121signalHandlerFunctionEiP9__siginfoPv + 152
12  libsystem_platform.dylib            0x000000018c56b584 _sigtramp + 56
13  libsystem_pthread.dylib             0x000000018c53ac20 pthread_kill + 288
14  libsystem_c.dylib                   0x000000018c447a30 abort + 180
15  libc++abi.dylib                     0x000000018c4f1d08 _ZN10__cxxabiv130__aligned_malloc_with_fallbackEm + 0
16  libc++abi.dylib                     0x000000018c4e1fc0 _ZL28demangling_terminate_handlerv + 348
17  libobjc.A.dylib                     0x000000018c1801d0 _ZL15_objc_terminatev + 144
18  libc++abi.dylib                     0x000000018c4f10cc _ZSt11__terminatePFvvE + 16
19  libc++abi.dylib                     0x000000018c4f1070 _ZSt9terminatev + 108
20  libtklo.dylib                       0x0000000104e0a440 _ZThn32_N11VCLXMenuBarD0Ev + 16
21  libfwklo.dylib                      0x00000001037fb0e4 _ZN9framework14MenuBarWrapper7disposeEv + 212
22  libfwklo.dylib                      0x000000010373fa70 _ZN9framework13LayoutManager19impl_clearUpMenuBarEv + 564
23  libfwklo.dylib                      0x000000010374105c _ZN9framework13LayoutManager22implts_destroyElementsEv + 116
24  libfwklo.dylib                      0x00000001037406a4 _ZN9framework13LayoutManager12implts_resetEb + 2576
25  libfwklo.dylib                      0x0000000103791e00 _ZN12_GLOBAL__N_110XFrameImpl27implts_sendFrameActionEventERKN3com3sun4star5frame11FrameActionE + 272
26  libfwklo.dylib                      0x0000000103789c1c _ZN12_GLOBAL__N_110XFrameImpl12setComponentERKN3com3sun4star3uno9ReferenceINS3_3awt7XWindowEEERKNS5_INS3_5frame11XControllerEEE + 304
27  libfwklo.dylib                      0x000000010378c1c8 _ZN12_GLOBAL__N_110XFrameImpl5closeEh + 340
28  libsfxlo.dylib                      0x0000000104363afc _ZN8SfxFrame7DoCloseEv + 220
29  libsvllo.dylib                      0x0000000104713c94 _ZN14SfxBroadcaster9BroadcastERK7SfxHint + 100
30  libsfxlo.dylib                      0x00000001042cc9b0 _ZThn40_N12_GLOBAL__N_121SfxModelListener_Impl13notifyClosingERKN3com3sun4star4lang11EventObjectE + 96
31  libsfxlo.dylib                      0x00000001042e0af0 _ZN12SfxBaseModel5closeEh + 620
32  libswlo.dylib                       0x000000042b5cfeac _ZN15SwXTextDocument5closeEh + 364
33  libgcc3_uno.dylib                   0x00000001025270fc _Z19callVirtualFunctionmPmS_S_iPv + 188
34  libgcc3_uno.dylib                   0x000000010252a1f4 _ZN12_GLOBAL__N_14callEPN7bridges7cpp_uno6shared17UnoInterfaceProxyENS2_10VtableSlotEP33_typelib_TypeDescriptionReferenceiP24_typelib_MethodParameterPvPSA_PP8_uno_Any + 2036
35  libgcc3_uno.dylib                   0x00000001025299cc unoInterfaceProxyDispatch + 616
36  libbinaryurplo.dylib                0x0000000106b55f18 _ZNK9binaryurp15IncomingRequest13execute_throwEPNS_9BinaryAnyEPNSt3__16vectorIS1_NS3_9allocatorIS1_EEEE + 1052
37  libbinaryurplo.dylib                0x0000000106b55708 _ZNK9binaryurp15IncomingRequest7executeEv + 128
38  libbinaryurplo.dylib                0x0000000106b5ba64 request + 44
39  libuno_cppu.dylib.3                 0x00000001026af398 _ZN15cppu_threadpool8JobQueue5enterEPKvb + 220
40  libuno_cppu.dylib.3                 0x00000001026b1ca8 _ZN15cppu_threadpool14ORequestThread3runEv + 144
41  libuno_cppu.dylib.3                 0x00000001026b1e74 threadFunc + 28
42  libuno_sal.dylib.3                  0x000000010266469c _ZL21osl_thread_start_ImplPv + 128
43  libsystem_pthread.dylib             0x000000018c53af94 _pthread_start + 136
44  libsystem_pthread.dylib             0x000000018c535d34 thread_start + 8
[MessageDispatcher] INFO org.jodconverter.local.office.OfficeConnection - Disconnected from 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
[MessageDispatcher] WARN org.jodconverter.local.office.LocalOfficeManagerPoolEntry - Connection lost unexpectedly; attempting restart
[MessageDispatcher] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Restarting due to lost connection...
[jodconverter-offprocmng-0] INFO org.jodconverter.local.office.LocalOfficeProcessManager - Process exited with code 134
Exception in thread "main" org.jodconverter.core.office.OfficeException: Task was cancelled: LocalConversionTask{source=SourceDocumentSpecsFromFile{file=DOCX_TestPage.docx, format=docx}, loadProperties={ReadOnly=true, Hidden=true, UpdateDocMode=0}, target=TargetDocumentSpecsFromFile{file=DOCX_TestPage.pdf, format=pdf}, storeProperties=null, useStreamAdapters=false}
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.waitTaskCompletion(AbstractOfficeManagerPoolEntry.java:101)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:86)
	at org.jodconverter.core.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:216)
	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:188)
	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:63)
	at jodTest.Test.main(Test.java:24)
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.waitTaskCompletion(AbstractOfficeManagerPoolEntry.java:95)
	... 5 more
```

**Comment by TJRoger** [comment]
same problem with LibreOffice 24.2.4.2 and jodconverter-local-lo 4.4.8 on M2 Pro macOS 14.1.1

**Comment by sbraconnier** [comment]
Sorry for the late answer. I don't have enough time to work on JODConverter. Is this still relevant ? If yes, could you please try using the libreoffice command line to see if the error also occurs without JODConverter?

 Thanks

**Comment by awidesky** [comment]
Hello! Glad to see the project is still active.

Currently I use JODConverter(local) 4.4.8 with homebrew libreoffice-still 24.8.7.2 (e07d0a63a46349d29051da79b1fde8160bab2a89)in the same macOS machine, and I cannot reproduce the error.
Neither JODconverter 4.4.7 or 4.4.8 makes the error with libreoffice 24.8.7.2
I guess it's fixed throughout updates in libreoffice(probably during 24.2.5 --> 24.8).

**Comment by sbraconnier** [comment]
Hello! Yes it is! 4.4.9 is out! Thanks for you feedback. I'll close this one for now, hopefully the problem won't return.
