### ISSUE TITLE
Could not open document with docx file，throwing NullPointerException

### ISSUE THREAD

**Issue by Holinc19** [jodconverter/jodconverter#407]
It throws NullPointerException, any help would be appreciated

```
2024-09-15 06:27:35.633  INFO 1 --- [ter-poolentry-3] o.j.local.task.LocalConversionTask       : Executing local conversion task [docx -> pdf]...
2024-09-15 06:27:35.653 ERROR 1 --- [ter-poolentry-3] o.j.local.task.LocalConversionTask       : Local conversion failed.

java.lang.NullPointerException: Could not open document: a522129e7f6a48b9989685e0830e208a@5febd3cafe234496bcc0a1a75d2043fb@CAXL2024592-1725526420492-订单合同_CAXL2024592 (2).docx
        at org.jodconverter.core.util.AssertUtils.notNull(AssertUtils.java:132) ~[jodconverter-core-4.4.6.jar!/:4.4.6]
        at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:210) ~[jodconverter-local-4.4.6.jar!/:4.4.6]
        at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:129) ~[jodconverter-local-4.4.6.jar!/:4.4.6]
        at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:121) [jodconverter-local-4.4.6.jar!/:4.4.6]
        at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:81) [jodconverter-core-4.4.6.jar!/:4.4.6]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_251]
```

**Comment by jonaskahn** [comment]
Same here

**Comment by jonaskahn** [comment]
I foundout that you should install libreoffice 7 to make it work correctly

**Comment by sbraconnier** [comment]
@Holinc19 Is this still relevant ? As @jonaskahn , you need LibreOffice version 7+ for docx file conversion.
