### ISSUE TITLE
On more recent Java version like Java 17, JODconverter has runtime exception Unable to create instance of class org.jodconverter.core.document.DocumentForma

### ISSUE THREAD

**Issue by tonggremlin** [jodconverter/jodconverter#408]
There is an RuntimeException as below when running JODCovnerter on more recent Java like Java 17 on JBossEAP 8.

`Caused by: java.lang.RuntimeException: Unable to create instance of class org.jodconverter.core.document.DocumentFormat. Registering an InstanceCreator or a TypeAdapter for this type, or adding a no-args constructor may fix this problem.
	at deployment.TestApp.war//com.google.gson.internal.ConstructorConstructor$19.construct(ConstructorConstructor.java:422)
	at deployment.TestApp.war//com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.createAccumulator(ReflectiveTypeAdapterFactory.java:552)
	at deployment.TestApp.war//com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:505)
	at deployment.TestApp.war//com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at deployment.TestApp.war//com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:83)
	at deployment.TestApp.war//com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:59)
	at deployment.TestApp.war//com.google.gson.Gson.fromJson(Gson.java:1361)
	at deployment.TestApp.war//com.google.gson.Gson.fromJson(Gson.java:1262)
	at deployment.TestApp.war//com.google.gson.Gson.fromJson(Gson.java:1171)
	at deployment.TestApp.war//com.google.gson.Gson.fromJson(Gson.java:1137)
	at deployment.TestApp.war//org.jodconverter.core.document.JsonDocumentFormatRegistry.readJsonArray(JsonDocumentFormatRegistry.java:114)
	at deployment.TestApp.war//org.jodconverter.core.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:81)
	at deployment.TestApp.war//org.jodconverter.core.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:53)
	at deployment.TestApp.war//org.jodconverter.core.document.DefaultDocumentFormatRegistryInstanceHolder.loadRegistry(DefaultDocumentFormatRegistryInstanceHolder.java:81)
	at deployment.TestApp.war//org.jodconverter.core.document.DefaultDocumentFormatRegistryInstanceHolder.getInstance(DefaultDocumentFormatRegistryInstanceHolder.java:46)
	at deployment.TestApp.war//org.jodconverter.core.document.DefaultDocumentFormatRegistry.getInstance(DefaultDocumentFormatRegistry.java:498)
	at deployment.TestApp.war//org.jodconverter.core.document.DefaultDocumentFormatRegistry.byExtension(DefaultDocumentFormatRegistry.java:502)
	at deployment.TestApp.war//org.jodconverter.core.document.DefaultDocumentFormatRegistry.<clinit>(DefaultDocumentFormatRegistry.java:61)
	... 82 more
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class org.jodconverter.core.document.DocumentFormat. Usage of JDK sun.misc.Unsafe is enabled, but it could not be used. Make sure your runtime is configured correctly.
	at deployment.TestApp.war//com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:121)
	at deployment.TestApp.war//com.google.gson.internal.ConstructorConstructor$19.construct(ConstructorConstructor.java:419)`

This is because GSON is trying to construct the `DocumentFormat` class and since it does not have no-args constructor then GSON choose to use sun.misc.Unsafe to create an instance. Usage of JDK sun.misc.Unsafe is now restricted by default as it leading to [an issue](https://stackoverflow.com/questions/18645050/is-default-no-args-constructor-mandatory-for-gson).

Either `DocumentFormat` need to be update to has no-args constructor or registering an InstanceCreator/TypeAdapter should resolve the issue.

**Comment by sbraconnier** [comment]
@tonggremlin Could you please try with the jodconverter 4.4.9-SNAPSHOT version using the sonatype snapshot repo:

https://oss.sonatype.org/content/repositories/snapshots

**Comment by lukasarc** [comment]
Hi, i ran into same issue just yesterday. Using the provided snapshot version (`4.4.9-SNAPSHOT`) resolves the issue. Thanks!

**Comment by tonggremlin** [comment]
@sbraconnier provided 4.4.9-SNAPSHOT resolve the issue. Thanks!

**Comment by tonggremlin** [comment]
Do we have an estimate of releasing "4.4.9"?

**Comment by sbraconnier** [comment]
Glad to hear the issue is now fixed. The release will by out by the end of the week.
